local ores = {"aluminium", "nickel", "zinc", "titanium", "cobalt", "drakestone", "bloodstone", "pyrite", "sunstone", "moonstone", "cryonite"}
local gemstones = {"ruby", "sapphire", "emerald", "amethyst", "onyx", "opal", "void"}
local exotic = {"elementium"}
local shards = {"prismarine"}

local values = {
	elementium = {
		disable_lump = true,
		full_punch_interval = {
			pickaxe = 1,
			sword = 0.5,
			axe = 1,
			shovel = 1,
		},
		groups = {
			pickaxe = {cracky={times={[1]=0.8,[2]=0.4, [3]=0.1}, uses=20, maxlevel=3}},
			sword = {snappy={times={[1]=0.8, [2]=0.2, [3]=0.05}, uses=20, maxlevel=3}},
			axe = {choppy={times={[1]=0.8, [2]=0.5, [3]=0.2}, uses=20, maxlevel=3}},
			shovel = {crumbly={times={[1]=0.8, [2]=0.1, [3]=0.05}, uses=20, maxlevel=3}},
		},
		damage_groups = {
			pick = {fleshy = 2},
			sword = {fleshy = 8},
			axe = {fleshy = 5},
			shovel = {fleshy = 2},
		},
		armor = {armor_use = 140, armor_heal = 25, special = {boots = {physics_gravity=0.3, physics_jump=1.9, physics_speed=1.7}}},
		--this not need to be generated by ores, inst a natural mineral, is a good element of the world.
	},
	void = {
		ores = {[1] = {y_max = -12000, y_min = -20000, clust_num_ores = 2, clust_scarcity = 27, clust_size = 3}},
		disable_lump = true,
	},
	opal = {
		--ores = {[1] = {y_max = -256, y_min = , clust_num_ores = 2, clust_scarcity = 27, clust_size = 3}},
		ores = {[1] = {y_max = 31000, y_min = -80}},
		--armor = {armor_use = 80, armor_heal = 17, special = {boots = {physics_gravity=0.9, physics_jump=1.3, physics_speed=1.2}}},
		disable_lump = true,
	},
	onyx = {
		full_punch_interval = {
			pickaxe = 1.2,
			sword = 0.8,
			axe = 1.1,
			shovel = 1.3,
		},
		groups = {
			pickaxe = {cracky={times={[1]=2,[2]=0.5, [3]=0.10}, uses=20, maxlevel=3}},
			sword = {snappy={times={[1]=2, [2]=0.5, [3]=0.10}, uses=20, maxlevel=3}},
			axe = {choppy={times={[1]=2, [2]=0.5, [3]=0.10}, uses=20, maxlevel=3}},
			shovel = {crumbly={times={[1]=2, [2]=0.5, [3]=0.1}, uses=20, maxlevel=3}},
		},
		damage_groups = {
			pickaxe = {fleshy = 1},
			sword = {fleshy = 6},
			axe = {fleshy = 3},
			shovel = {fleshy = 2},
		},
		--ores = {[1] = {y_max = -256, y_min = , clust_num_ores = 2, clust_scarcity = 27, clust_size = 3}},
		ores = {[1] = {}},
		armor = {armor_use = 80, armor_heal = 17, special = {boots = {physics_gravity=0.2, physics_jump=1.3, physics_speed=1.2}}},
		--disable_lump = true,
	},
	cryonite = {
		full_punch_interval = {
			pickaxe = 1.2,
			sword = 0.8,
			axe = 1.1,
			shovel = 1.3,
		},
		groups = {
			pickaxe = {cracky={times={[1]=2,[2]=1, [3]=0.5}, uses=15, maxlevel=3}},
			sword = {snappy={times={[1]=2.4, [2]=1, [3]=0.3}, uses=15, maxlevel=3}},
			axe = {choppy={times={[1]=2, [2]=1, [3]=0.6}, uses=15, maxlevel=3}},
			shovel = {crumbly = {times={[1]=2, [2]=1, [3]=0.10}, uses=15, maxlevel=3}},
		},
		damage_groups = {
			pickaxe = {fleshy = 2},
			sword = {fleshy = 6},
			axe = {fleshy = 5},
			shovel = {fleshy = 2},
		},
		ores = {[1] = {y_max = 500, y_min = -100, clust_num_ores = 10, clust_scarcity = 4000, clust_size = 8, wherein = "default:ice", orename = "cryonite:ice_with_cryonite"}},
		armor = {armor_use = 130, armor_heal = 17, special = {boots = {physics_gravity=0.7, physics_jump=1.5, physics_speed=1}}},
		orenodes = {
			[1] = {
				name = "cryonite:ice_with_cryonite",
				description = "Ice with Cryonite",
				tiles = {"engine_ice_with_cryonite.png"},
				drop = "cryonite:cryonite_lump",
			}
		}
	},
	moonstone = {
		full_punch_interval = {
			pickaxe = 1.2,
			sword = 0.8,
			axe = 1.1,
			shovel = 1.3,
		},
		groups = {
			pickaxe = {cracky={times={[1]=1,[2]=0.6, [3]=0.1}, uses=35, maxlevel=3}},
			sword = {snappy={times={[1]=1, [2]=0.6, [3]=0.1}, uses=35, maxlevel=3}},
			axe = {choppy={times={[1]=1, [2]=0.6, [3]=0.1}, uses=35, maxlevel=3}},
			shovel = {crumbly = {times={[1]=1, [2]=0.6, [3]=0.1}, uses=35, maxlevel=3}},
		},
		damage_groups = {
			pickaxe = {fleshy = 2},
			sword = {fleshy = 8},
			axe = {fleshy = 4},
			shovel = {fleshy = 2},
		},
		ores = {[1] = {y_max = 10200, y_min = 100, clust_num_ores = 2, clust_scarcity = 27, clust_size = 3}},
		armor = {armor_use = 130, armor_heal = 17, special = {boots = {physics_gravity=0.09, physics_jump=1.5, physics_speed=1}}}
	},
	sunstone = {
		full_punch_interval = {
			pickaxe = 1.2,
			sword = 0.8,
			axe = 1.1,
			shovel = 1.3,
		},
		groups = {
			pickaxe = {cracky={times={[1]=1,[2]=0.6, [3]=0.1}, uses=35, maxlevel=3}},
			sword = {snappy={times={[1]=1, [2]=0.6, [3]=0.1}, uses=35, maxlevel=3}},
			axe = {choppy={times={[1]=1, [2]=0.6, [3]=0.1}, uses=35, maxlevel=3}},
			shovel = {crumbly = {times={[1]=1, [2]=0.6, [3]=0.1}, uses=35, maxlevel=3}},
		},
		damage_groups = {
			pickaxe = {fleshy = 3},
			sword = {fleshy = 9},
			axe = {fleshy = 5},
			shovel = {fleshy = 1},
		},
		ores = {[1] = {y_max = 900, y_min = 100, clust_num_ores = 2, clust_scarcity = 27, clust_size = 3}},
		armor = {armor_use = 130, armor_heal = 17, special = {boots = {physics_gravity=1.3, physics_jump=1.3, physics_speed=1.7}}}
	},
	pyrite = { -- F O O L
		full_punch_interval = {
			pickaxe = 1.2,
			sword = 0.8,
			axe = 1.1,
			shovel = 1.3,
		},
		groups = {
			pickaxe = {cracky={times={[1]=3,[2]=2.1, [3]=0.8}, uses=15, maxlevel=3}},
			sword = {snappy={times={[1]=2.5, [2]=1.2, [3]=0.6}, uses=15, maxlevel=3}},
			axe = {choppy={times={[1]=2, [2]=1.20, [3]=0.80}, uses=15, maxlevel=3}},
			shovel = {crumbly = {times={[1]=2, [2]=1.20, [3]=0.80}, uses=15, maxlevel=3}},
		},
		damage_groups = {
			pickaxe = {fleshy = 1},
			sword = {fleshy = 5},
			axe = {fleshy = 4},
			shovel = {fleshy = 1},
		},
		ores = {[1] = {y_max = 10, y_min = -31000}},
		armor = {armor_use = 90, armor_heal = 12}
	},
	bloodstone = {
		ores = {[1] = {y_max = -4000, y_min = -31000}},
	},
	drakestone = {
		full_punch_interval = {
			pickaxe = 1.1,
			sword = 0.5,
			axe = 1.1,
			shovel = 1.3,
		},
		groups = {
			pickaxe = {cracky={times={[1]=1.2,[2]=0.6, [3]=0.1}, uses=30, maxlevel=3}},
			sword = {snappy={times={[1]=1, [2]=0.8, [3]=0.4}, uses=30, maxlevel=3}},
			axe = {choppy={times={[1]=0.90, [2]=0.20, [3]=0.10}, uses=30, maxlevel=3}},
			shovel = {crumbly = {times={[1]=0.50, [2]=0.20, [3]=0.10}, uses=30, maxlevel=3}},
		},
		damage_groups = {
			pickaxe = {fleshy = 2},
			sword = {fleshy = 7},
			axe = {fleshy = 5},
			shovel = {fleshy = 3},
		},
		ores = {[1] = {y_max = -4000, y_min = -31000}},
		armor = {armor_use = 120, armor_heal = 15}
	},
	cobalt = {
		full_punch_interval = {
			pickaxe = 1.1,
			sword = 0.6,
			axe = 1.1,
			shovel = 1.3,
		},
		groups = {
			pickaxe = {cracky={times={[1]=1.5,[2]=0.7, [3]=0.25}, uses=20, maxlevel=3}},
			sword = {snappy={times={[1]=1.20, [2]=0.90, [3]=0.50}, uses=20, maxlevel=3}},
			axe = {choppy={times={[1]=1.20, [2]=0.20, [3]=0.80}, uses=20, maxlevel=3}},
			shovel = {crumbly = {times={[1]=0.90, [2]=0.80, [3]=0.60}, uses=20, maxlevel=3}},
		},
		damage_groups = {
			pickaxe = {fleshy = 1},
			sword = {fleshy = 6},
			axe = {fleshy = 4},
			shovel = {fleshy = 2},
		},
		ores = {[1] = {y_max = -300, y_min = -31000}},
		armor = {armor_use = 100, armor_heal = 12}
	},
	titanium = {
		full_punch_interval = {
			pickaxe = 1.1,
			sword = 0.6,
			axe = 1.1,
			shovel = 1.3,
		},
		groups = {
			pickaxe = {cracky = {times={[1]=2.30, [2]=0.60, [3]=0.30}, uses=35, maxlevel=3}},
			sword = {snappy={times={[1]=2.7, [2]=1.40, [3]=0.65}, uses=35, maxlevel=3}},
			axe = {choppy={times={[1]=1.20, [2]=0.80, [3]=0.30}, uses=35, maxlevel=3}},
			shovel = {crumbly = {times={[1]=1.20, [2]=1.10, [3]=0.60}, uses=35, maxlevel=3}},
		},
		damage_groups = {
			pickaxe = {fleshy = 2},
			sword = {fleshy = 5},
			axe = {fleshy = 6},
			shovel = {fleshy = 2},
		},
		ores = {[1] = {y_max = -300, y_min = -31000}},
		armor = {armor_use = 100, armor_heal = 16}
	},
	aluminium = {
		full_punch_interval = {
			pickaxe = 1.0,
			sword = 0.8,
			axe = 1.2,
			shovel = 1.1,
		},
		groups = {
			pickaxe = {cracky = {times={[1]=4.30, [2]=1.90, [3]=1.20}, uses=20, maxlevel=2}},
			sword = {snappy={times={[1]=2.7, [2]=1.40, [3]=0.65}, uses=31, maxlevel=2}},
			axe = {choppy={times={[1]=2.40, [2]=1.20, [3]=0.80}, uses=20, maxlevel=3}},
			shovel = {crumbly = {times={[1]=1.70, [2]=1.10, [3]=0.60}, uses=30, maxlevel=2}},
		},
		damage_groups = {
			pickaxe = {fleshy = 2},
			sword = {fleshy = 4},
			axe = {fleshy = 5},
			shovel = {fleshy = 3},
		},
	},
	nickel = {
		full_punch_interval = {
			pickaxe = 1.0,
			sword = 0.8,
			axe = 1.2,
			shovel = 1.1,
		},
		groups = {
			pickaxe = {cracky = {times={[1]=4.30, [2]=1.90, [3]=1.20}, uses=20, maxlevel=2}},
			sword = {snappy={times={[1]=2.7, [2]=1.40, [3]=0.65}, uses=31, maxlevel=2}},
			axe = {choppy={times={[1]=2.40, [2]=1.20, [3]=0.80}, uses=20, maxlevel=3}},
			shovel = {crumbly = {times={[1]=1.70, [2]=1.10, [3]=0.60}, uses=30, maxlevel=2}},
		},
		damage_groups = {
			pickaxe = {fleshy = 2},
			sword = {fleshy = 4},
			axe = {fleshy = 5},
			shovel = {fleshy = 3},
		},
		ores = {[1] = {}}, --leave empty for default thing
	},
	zinc = {
		full_punch_interval = {
			pickaxe = 1.0,
			sword = 0.8,
			axe = 1.2,
			shovel = 1.1,
		},
		groups = {
			pickaxe = {cracky = {times={[1]=4.30, [2]=1.90, [3]=1.20}, uses=20, maxlevel=2}},
			sword = {snappy={times={[1]=2.7, [2]=1.40, [3]=0.65}, uses=31, maxlevel=2}},
			axe = {choppy={times={[1]=2.40, [2]=1.20, [3]=0.80}, uses=20, maxlevel=3}},
			shovel = {crumbly = {times={[1]=1.70, [2]=1.10, [3]=0.60}, uses=30, maxlevel=2}},
		},
		damage_groups = {
			pickaxe = {fleshy = 2},
			sword = {fleshy = 4},
			axe = {fleshy = 5},
			shovel = {fleshy = 3},
		},
		ores = {
			[1] = {
				y_max = -256,
				y_min = -31000,
				clust_scarcity = 15 * 15 * 15,
			},
			[2] = {
				y_max = -128,
				y_min = -255,
				clust_scarcity = 17 * 17 * 17,
			},
			[3] = {
				y_max = -256,
				y_min = -31000,
				clust_scarcity = 15 * 15 * 15,
			},
		},
		armor = {
			armor_heal = 15, --For boots, leggings, chestplate, helmet and shield
			armor_use = 70,
			--[[special = {
				boots = {physics_speed=1.5}
			}--]]
		},
		--[[orenodes = {
			[1] = {
				name = "name:name",
				description = "idk",
				tiles = {"varoom.png"},
			}
		}--]]
	}
}

--Use the automatic register, not filling the entire document gaining more than 20.000bytes

local t = TransformTextReadable

------------
for _, ore in pairs({"amethyst", "ruby", "emerald", "sapphire"}) do
	core.register_node(":"..ore..":"..ore.."_block", {
		description = (t(ore).." Block"),
		tiles = {ore.."_block.png"},
		is_ground_content = true,
		groups = {cracky = 3},
	})
	core.register_node(":"..ore..":"..ore.."_ore", {
		description = (t(ore).." Ore"),
		tiles = {"default_stone.png^"..ore.."_ore.png"},
		is_ground_content = true,
		groups = {cracky = 3, ore = 1},
		drop = ore..":"..ore.."_ingot",
	})
	core.register_craftitem(":"..ore..":"..ore.."_ingot", {
		description = (t(ore).." Gem"),
		inventory_image = ore..".png",
	})
	core.register_tool(":"..ore..":"..ore.."_sword", {
		description = t(ore).." Sword",
		inventory_image = ore.."_sword.png",
		tool_capabilities = {
			full_punch_interval = 0.5,
			max_drop_level=1,
			groupcaps={
				snappy={times={[1]=1.90, [2]=0.90, [3]=0.30}, uses=40, maxlevel=3},
			},
			damage_groups = {fleshy=8},
		},
		sound = {breaks = "default_tool_breaks"},
		groups = {sword = 1}
	})
	core.register_tool(":"..ore..":"..ore.."_pickaxe", {
		description = t(ore).." Pickaxe",
		inventory_image = ore.."_pickaxe.png",
		tool_capabilities = {
			full_punch_interval = 0.5,
			max_drop_level=3,
			groupcaps={
				cracky = {times={[1]=2.0, [2]=1.0, [3]=0.50}, uses=80, maxlevel=3},
			},
			damage_groups = {fleshy=5},
		},
		sound = {breaks = "default_tool_breaks"},
		groups = {pickaxe = 1}
	})
	core.register_tool(":"..ore..":"..ore.."_axe", {
		description = t(ore).." Axe",
		inventory_image = ore.."_axe.png",
		tool_capabilities = {
			full_punch_interval = 0.5,
			max_drop_level=1,
			groupcaps={
				choppy={times={[1]=2.10, [2]=0.90, [3]=0.50}, uses=80, maxlevel=3},
			},
			damage_groups = {fleshy=7},
		},
		sound = {breaks = "default_tool_breaks"},
		groups = {axe = 1}
	})
	core.register_tool(":"..ore..":"..ore.."_shovel", {
		description = t(ore).." Shovel",
		inventory_image = ore.."_shovel.png",
		tool_capabilities = {
		full_punch_interval = 0.5,
			max_drop_level=1,
			groupcaps={
				crumbly = {times={[1]=1.10, [2]=0.50, [3]=0.30}, uses=80, maxlevel=3},
			},
			damage_groups = {fleshy=4},
		},
		sound = {breaks = "default_tool_breaks"},
		groups = {shovel = 1}
	})
	core.register_ore({
		ore_type       = "scatter",
		ore            = ore..":"..ore.."_ore",
		wherein        = "default:stone",
		clust_scarcity = 15 * 15 * 15,
		clust_num_ores = 4,
		clust_size     = 3,
		y_max          = -256,
		y_min          = -31000,
		})
	core.register_ore({
		ore_type       = "scatter",
		ore            = ore..":"..ore.."_ore",
		wherein        = "default:stone",
		clust_scarcity = 17 * 17 * 17,
		clust_num_ores = 4,
		clust_size     = 3,
		y_max          = -128,
		y_min          = -255,
	})
	core.register_ore({
		ore_type       = "scatter",
		ore            = ore..":"..ore.."_ore",
		wherein        = "default:stone",
		clust_scarcity = 15 * 15 * 15,
		clust_num_ores = 4,
		clust_size     = 3,
		y_max          = -256,
		y_min          = -31000,
	})
	core.register_craft({
		output = ore..":"..ore.."_sword",
		recipe = {
			{ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot"},
			{"group:stick"},
		}
	})
	core.register_craft({
		output = ore..":"..ore.."_pickaxe",
		recipe = {
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{"", "group:stick", ""},
			{"", "group:stick", ""},
		}
	})
	core.register_craft({
		output = ore..":"..ore.."_shovel",
		recipe = {
			{ore..":"..ore.."_ingot"},
			{"group:stick"},
			{"group:stick"},
		}
	})
	core.register_craft({
		output = ore..":"..ore.."_axe",
		recipe = {
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", "group:stick"},
			{"", "group:stick"},
		}
	})
	core.register_craft({
		output = ore..":"..ore.."_block",
		recipe = {
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
		}
	})
	core.register_craft({
		output = ore..":"..ore.."_ingot 9",
		recipe = {
			{ore..":"..ore.."_block"},
		}
	})
	core.register_craft({
		output = ore..":helmet_"..ore,
		recipe = {
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{"", "", ""},
		}
	})
	core.register_craft({
		output = ore..":chestplate_"..ore,
		recipe = {
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
		}
	})
	core.register_craft({
		output = ore..":leggings_"..ore,
		recipe = {
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
		}
	})
	core.register_craft({
		output = ore..":boots_"..ore,
		recipe = {
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{"", "", ""},
		}
	})
	core.register_craft({
		output = ore..":shield_"..ore,
		recipe = {
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{"", ore..":"..ore.."_ingot", ""},
		}
	})
	if core.get_modpath("3d_armor") then
		armor:register_armor(":"..ore..":helmet_"..ore, {
			description = (t(ore).." Helmet"),
			inventory_image = ore.."_helmet_inv.png",
			groups = {armor_head=1, armor_heal=16, armor_use=70},
			armor_groups = {fleshy=10},
			damage_groups = {cracky=2, snappy=1, level=6},
		})
		armor:register_armor(":"..ore..":leggings_"..ore, {
			description = (t(ore).." Leggings"),
			inventory_image = ore.."_leggings_inv.png",
			groups = {armor_legs=1, armor_heal=16, armor_use=70},
			armor_groups = {fleshy=30},
			damage_groups = {cracky=2, snappy=1, level=6},
		})
		armor:register_armor(":"..ore..":chestplate_"..ore, {
			description = (t(ore).." Chestplate"),
			inventory_image = ore.."_chestplate_inv.png",
			groups = {armor_torso=1, armor_heal=16, armor_use=70},
			armor_groups = {fleshy=30},
			damage_groups = {cracky=2, snappy=1, level=6},
		})
		armor:register_armor(":"..ore..":boots_"..ore, {
			description = (t(ore).." Boots"),
			inventory_image = ore.."_boots_inv.png",
			groups = {armor_feet=1, armor_heal=16, armor_use=70, physics_speed=1.5},
			armor_groups = {fleshy=10},
			damage_groups = {cracky=2, snappy=1, level=6},
		})
		armor:register_armor(":"..ore..":shield_"..ore, {
			description = (t(ore).." Shield"),
			inventory_image = ore.."_shield_inv.png",
			groups = {armor_shield=1, armor_heal=12, armor_use=70},
			armor_groups = {fleshy=10},
			damage_groups = {cracky=2, snappy=1, level=6},
		})
	end
end

local function translate_character(c)
	if c == "helmet" then
		return "head"
	elseif c == "chestplate" then
		return "torso"
	elseif c == "leggings" then
		return "legs"
	elseif c == "boots" then
		return "feet"
	else
		return c
	end
end

--Register everything

for element, data in pairs(values) do
	--Ingot
	core.register_craftitem(":"..element..":"..element.."_ingot", {
		description = (TransformTextReadable(element).." Ingot"),
		inventory_image = element..".png",
	})
	--Lump
	if not data.disable_lump then
		core.register_craftitem(":"..element..":"..element.."_lump", {
			description = (TransformTextReadable(element).." Lump"),
			inventory_image = element.."_lump.png",
		})
		core.register_craft({
			type = "cooking",
			output = element..":"..element.."_ingot",
			recipe = element..":"..element.."_lump",
		})
	end
	--Block (Always need to be cracky 3)
	core.register_node(":"..element..":"..element.."_block", {
		description = (TransformTextReadable(element).." Block"),
		tiles = {element.."_block.png"},
		is_ground_content = true,
		groups = {cracky = 3},
	})
	--Tools [Simplified]
	for _, inf in pairs({"Pickaxe", "Axe", "Shovel", "Sword"}) do
		if data.groups and data.groups[(inf:lower())] then
			core.register_tool(":"..element..":"..element.."_"..(inf:lower()), {
				description = TransformTextReadable(element).." "..inf,
				inventory_image = element.."_"..inf:lower()..".png",
				tool_capabilities = {
					full_punch_interval = 0.5,
					max_drop_level = 1,
					groupcaps = data.groups[(inf:lower())],
					damage_groups = data.damage_groups[(inf:lower())],
				},
				sound = {breaks = "default_tool_breaks"},
				groups = {[(inf:lower())] = 1}
			})
		end
	end
	--Armor
	if core.get_modpath("3d_armor") then
		if data.armor then
			for _, inf in pairs({"Chestplate", "Boots", "Leggings", "Shield", "Helmet"}) do
				local lower = inf:lower()
				
				local groups = {}--{["armor_"..lower]=1, armor_heal=data.armor.armor_heal, armor_use=data.armor.armor_use}
				
				if data.armor.special and data.armor.special[lower] then
					groups = data.armor.special[lower]
				end
				
				groups["armor_"..translate_character(lower)] = 1
				groups.armor_heal = groups.armor_heal or data.armor.armor_heal
				groups.armor_use = groups.armor_use or data.armor.armor_use
				
				armor:register_armor(":"..element..":"..lower.."_"..element, {
					description = (TransformTextReadable(element).." "..inf),
					inventory_image = element.."_"..lower.."_inv.png",
					groups = groups,
					armor_groups = {fleshy=10},
					texture = element.."_"..lower..".png",
					damage_groups = {cracky=2, snappy=1, level=6},
				})
			end
		end
	end
	--Ore
	if data.ores then
		if data.orenodes then
			for I, datas in pairs(data.orenodes) do
				core.register_node(":"..datas.name or (":"..element..":"..element.."_ore"), {
					description = datas.description or (TransformTextReadable(element).." Ore"),
					tiles = datas.tiles or {"default_stone.png^"..element.."_ore.png"},
					is_ground_content = true,
					groups = {cracky = 3, ore = 1},
					drop = datas.drop or ((not data.disable_lump) and (element..":"..element.."_lump")) or (element..":"..element.."_ingot"),
				})
			end
		else
			core.register_node(":"..element..":"..element.."_ore", {
				description = (TransformTextReadable(element).." Ore"),
				tiles = {"default_stone.png^"..element.."_ore.png"},
				is_ground_content = true,
				groups = {cracky = 3, ore = 1},
				drop = ((not data.disable_lump) and (element..":"..element.."_lump")) or (element..":"..element.."_ingot"),
			})
		end
		for I, datas in pairs(data.ores) do
			core.register_ore({
				ore_type       = "scatter",
				ore            = datas.orename or (element..":"..element.."_ore"),
				wherein        = datas.wherein or ("default:stone"),
				clust_scarcity = datas.clust_scarcity or 3375,
				clust_num_ores = datas.clust_num_ores or 4,
				clust_size     = datas.clust_size or 3,
				y_max          = datas.y_max or -256,
				y_min          = datas.y_min or -31000,
			})
		end
	end
	--Recipes (STATIC!)
	local ore = element
	core.register_craft({
		output = ore..":"..ore.."_sword",
		recipe = {
			{ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot"},
			{"group:stick"},
		}
	})
	core.register_craft({
		output = ore..":"..ore.."_pickaxe",
		recipe = {
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{"", "group:stick", ""},
			{"", "group:stick", ""},
		}
	})
	core.register_craft({
		output = ore..":"..ore.."_shovel",
		recipe = {
			{ore..":"..ore.."_ingot"},
			{"group:stick"},
			{"group:stick"},
		}
	})
	core.register_craft({
		output = ore..":"..ore.."_axe",
		recipe = {
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", "group:stick"},
			{"", "group:stick"},
		}
	})
	core.register_craft({
		output = ore..":"..ore.."_block",
		recipe = {
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
		}
	})
	core.register_craft({
		output = ore..":"..ore.."_ingot 9",
		recipe = {
			{ore..":"..ore.."_block"},
		}
	})
	core.register_craft({
		output = ore..":helmet_"..ore,
		recipe = {
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{"", "", ""},
		}
	})
	core.register_craft({
		output = ore..":chestplate_"..ore,
		recipe = {
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
		}
	})
	core.register_craft({
		output = ore..":leggings_"..ore,
		recipe = {
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
		}
	})
	core.register_craft({
		output = ore..":boots_"..ore,
		recipe = {
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{"", "", ""},
		}
	})
	core.register_craft({
		output = ore..":shield_"..ore,
		recipe = {
			{ore..":"..ore.."_ingot", "", ore..":"..ore.."_ingot"},
			{ore..":"..ore.."_ingot", ore..":"..ore.."_ingot", ore..":"..ore.."_ingot"},
			{"", ore..":"..ore.."_ingot", ""},
		}
	})
end

--Special

MineStars.Workbench.RegisterMalletResult({
	input = "onyx:onyx_lump",
	output = "onyx:onyx_ingot"
})
--[[
core.register_craft({
	output = "elementium:elementiun_ingot",
	recipe = {
		{"engine:heaven_stone", "sunstone:sunstone_ingot", ""},
		{"moonstone:moonstone_ingot", "bloodstone:bloodstone_ingot", ""},
		{"","",""}
	}
})


--]]





























